def irs_position_trade(position,wb):
    p_type=list(wb[wb["trade_code"]==position]["type"])[0]
    irsDefinition={}
    fixedleg={}
    floatingleg={}
    #fixedleg["payOrReceive"]=list(wb[wb["trade_code"]==position]["fixedlegpayOrReceive"])[0]
    fixedleg["frequency"]=list(wb[wb["trade_code"]==position]["fixedlegfrequency"])[0]
    fixedleg["coupon"]=list(wb[wb["trade_code"]==position]["fixedlegcoupon"])[0]
    fixedleg["calendar"]=list(wb[wb["trade_code"]==position]["fixedlegcalendar"])[0]
    fixedleg["dateGeneration"]="Backward"
    fixedleg["dayCounter"]=list(wb[wb["trade_code"]==position]["fixedlegdayCounter"])[0]
    fixedleg["businessDayConvention"]="ModifiedFollowing"
    fixedleg["maturityDateConvention"]="ModifiedFollowing"
    fixedleg["endOfMonth"]=True
    floatingleg["frequency"]=list(wb[wb["trade_code"]==position]["floatinglegfrequency"])[0]
    floatingleg["spread"]=list(wb[wb["trade_code"]==position]["floatinglegspread"])[0]
    floatingleg["calendar"]=list(wb[wb["trade_code"]==position]["floatinglegcalendar"])[0]
    floatingleg["dateGeneration"]="Backward"
    floatingleg["dayCounter"]=list(wb[wb["trade_code"]==position]["floatinglegdayCounter"])[0]
    floatingleg["businessDayConvention"]="ModifiedFollowing"
    floatingleg["maturityDateConvention"]="ModifiedFollowing"
    floatingleg["endOfMonth"]=True
    floatingleg["fixingDate"]=[]
    floatingleg["fixingRate"]=[]
    irsDefinition["fixedleg"]=fixedleg
    irsDefinition["floatingleg"]=floatingleg
    irsDefinition["type"]="IRSDefinition"
    irsDefinition["calculator"]="interest_rates_swap"
    irsDefinition["startDate"]=list(wb[wb["trade_code"]==position]["startDate"])[0].strftime("%Y-%m-%d")
    irsDefinition["maturityDate"]=list(wb[wb["trade_code"]==position]["maturityDate"])[0].strftime("%Y-%m-%d")
    irsDefinition["discountCurve"]="TRYZC"
    irsDefinition["floatingLegForecastCurve"]="TRYZC"
    irsDefinition["currency"]="TRY"
    result=irsDefinition 
    return result