def swap_position_trade(position,wb):
    p_type=list(wb[wb["trade_code"]==position]["type"])[0]
    swapDefinition={}
    shortleg={}
    longleg={}
    #shortleg["notional"]=list(wb[wb["trade_code"]==position]["shortLegNotional"])[0]
    shortleg["currency"]=list(wb[wb["trade_code"]==position]["sellLegCurrency"])[0]
    shortleg["dayCounter"]=list(wb[wb["trade_code"]==position]["sellLegdayCounter"])[0]
    shortleg["calendar"]=list(wb[wb["trade_code"]==position]["sellLegcalendar"])[0]
    shortleg["businessDayConvention"]="ModifiedFollowing"
    shortleg["endOfMonth"]=True
    #longleg["notional"]=list(wb[wb["trade_code"]==position]["buyLegNotional"])[0]
    longleg["currency"]=list(wb[wb["trade_code"]==position]["buyLegCurrency"])[0]
    longleg["dayCounter"]=list(wb[wb["trade_code"]==position]["buyLegdayCounter"])[0]
    longleg["calendar"]=list(wb[wb["trade_code"]==position]["buyLegcalendar"])[0]
    longleg["businessDayConvention"]="ModifiedFollowing"
    longleg["endOfMonth"]=True
    swapDefinition["shortLeg"]=shortleg
    swapDefinition["longLeg"]=longleg
    swapDefinition["type"]="FXSwapDefinition"
    swapDefinition["calculator"]="fx_swap"
    swapDefinition["maturityDate"]=list(wb[wb["trade_code"]==position]["maturityDate"])[0].strftime("%Y-%m-%d")
    swapDefinition["startDate"]=list(wb[wb["trade_code"]==position]["startDate"])[0].strftime("%Y-%m-%d")
    swapDefinition["shortLegDiscountCurve"]="TRYZC"
    swapDefinition["longLegDiscountCurve"]="TRYZC"
    swapDefinition["strike"]=list(wb[wb["trade_code"]==position]["strike"])[0]
    swapDefinition["spotPrice"]=7.5109
    result=swapDefinition 
    return result